sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t viratarya/docker-react -f Dockerfile.dev .
#- docker run -e CI=true USERNAME/docker-react npm run test
#language: generic

script:
  - docker run -e CI=true viratarya/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-503476296549"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

#  Dockerreact-env.eba-pnejnjsf.us-east-1.elasticbeanstalk.com
